ALTER TABLE CUSTOMERS
ADD ISVIP VARCHAR2(5) DEFAULT 'FALSE';

BEGIN
	FOR RES IN (
		SELECT CUSTOMERID, BALANCE FROM CUSTOMERS
	) LOOP
		IF RES.BALANCE > 10000 THEN
			UPDATE CUSTOMERS
			SET ISVIP = 'TRUE'
			WHERE CUSTOMERID = RES.CUSTOMERID;
		END IF;
	END LOOP;

	COMMIT;
END;